#!/bin/bash
source /home/pc14c/miniconda3/etc/profile.d/conda.sh
conda activate buffer_env

set -e

BAM_DIR="../Results/Mapping/unmapped"
KRAKEN_DB="/home/pc14c/kraken2db"
OUT="../Results/Microbiome"
THREADS=5
PARALLEL_JOBS=2

mkdir -p "$OUT"

export BAM_DIR KRAKEN_DB OUT THREADS

find "$BAM_DIR" -name "*.unmapped.align.sort.bam" | sort | xargs -P "$PARALLEL_JOBS" -I{} bash -c '
    bam="{}"
    SAMPLE=$(basename "$bam" .unmapped.align.sort.bam)

    echo "Processing $SAMPLE"

    # Convert BAM to FASTQ
    samtools fastq -n \
        -1 "$BAM_DIR/${SAMPLE}_1.fastq" \
        -2 "$BAM_DIR/${SAMPLE}_2.fastq" \
        -s "$BAM_DIR/${SAMPLE}_singletons.fastq" \
        "$bam"

    # Run Kraken2
    kraken2 --db "$KRAKEN_DB" \
        --threads "$THREADS" \
        --output "$OUT/${SAMPLE}_taxonomy" \
        --report "$OUT/${SAMPLE}_taxonomy_kreport" \
        --paired "$BAM_DIR/${SAMPLE}_1.fastq" \
                 "$BAM_DIR/${SAMPLE}_2.fastq"

    # Krona visualization
    kreport2krona.py \
        -r "$OUT/${SAMPLE}_taxonomy_kreport" \
        -o "$OUT/${SAMPLE}_krona"

    ktImportText "$OUT/${SAMPLE}_krona" -o "$OUT/${SAMPLE}.html"

    echo "$SAMPLE done"
'

echo "All samples done!"
conda deactivate
